version: '3.7'

services:
  bot:
    container_name: reminder-bot
    build: .
    env_file:
      - .env
    ports:
      - '8989:8989'
networks:
  default:
    name: bridge-nerwork
    external: true
